
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:23 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 23.6.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin//armclang 
      Build flags: --target=arm-arm-none-eabi;-mcpu=cortex-m0plus;-mfpu=none
      Id flags: -c;--target=arm-arm-none-eabi 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is ARMClang, found in:
        /Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/3.28.4/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" matched "armclang":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes"
      binary: "/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes"
    cmakeVariables:
      CMAKE_CXX_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "--target=arm-arm-none-eabi -mcpu=cortex-m0plus -mfpu=none"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.open.cmsis.pack.cmsis.toolbox/2.6.1/etc/CMakeASM"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes'
        
        Run Build Command(s): /Users/amr/.vcpkg/artifacts/2139c4c6/tools.ninja.build.ninja/1.12.0/ninja -v cmTC_95dbb
        [1/2] /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin//armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=cortex-m0plus -mfpu=none    -v -MD -MT CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -c /Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Product: Keil MDK Community (non-commercial free of charge)
        Component: Arm Compiler for Embedded 6.23
        Tool: armclang [5f103000]
        
        Target: arm-arm-none-eabi
         (in-process)
         "/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/armclang" -cc1 -triple thumbv6m-arm-none-eabi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m0plus -target-feature +soft-float-abi -target-feature -crc -target-feature -dsp -target-feature -mve -target-feature -ras -target-feature -sb -target-feature -i8mm -target-feature -lob -target-feature -cdecp0 -target-feature -cdecp1 -target-feature -cdecp2 -target-feature -cdecp3 -target-feature -cdecp4 -target-feature -cdecp5 -target-feature -cdecp6 -target-feature -cdecp7 -target-feature -pacbti -target-feature -fce -target-feature -hwdiv-arm -target-feature -hwdiv -target-feature -vfp2 -target-feature -vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature -vfp3d16sp -target-feature -vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -dotprod -target-feature -fp16fml -target-feature -bf16 -target-feature -mve.fp -target-feature -fpregs -target-feature -crypto -target-feature -sha2 -target-feature -aes -target-feature +strict-align -target-abi aapcs -mfloat-abi soft -Wunaligned-access -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes -resource-dir /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/lib/clang/20 -dependency-file CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -x c /Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Arm Compiler for Embedded 6.23 -cc1 default target aarch64-arm-none-eabi
        #include "..." search starts here:
        #include <...> search starts here:
         /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include
        End of search list.
        [2/2] : && /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/armar --create -cr libcmTC_95dbb.a  CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include]
        end of search list found
        collapse include dir [/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include] ==> [/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/include]
        implicit include dirs: [/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes']
        ignore line: []
        ignore line: [Run Build Command(s): /Users/amr/.vcpkg/artifacts/2139c4c6/tools.ninja.build.ninja/1.12.0/ninja -v cmTC_95dbb]
        ignore line: [[1/2] /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin//armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=cortex-m0plus -mfpu=none    -v -MD -MT CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -c /Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Product: Keil MDK Community (non-commercial free of charge)]
        ignore line: [Component: Arm Compiler for Embedded 6.23]
        ignore line: [Tool: armclang [5f103000]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "/Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/armclang" -cc1 -triple thumbv6m-arm-none-eabi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m0plus -target-feature +soft-float-abi -target-feature -crc -target-feature -dsp -target-feature -mve -target-feature -ras -target-feature -sb -target-feature -i8mm -target-feature -lob -target-feature -cdecp0 -target-feature -cdecp1 -target-feature -cdecp2 -target-feature -cdecp3 -target-feature -cdecp4 -target-feature -cdecp5 -target-feature -cdecp6 -target-feature -cdecp7 -target-feature -pacbti -target-feature -fce -target-feature -hwdiv-arm -target-feature -hwdiv -target-feature -vfp2 -target-feature -vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature -vfp3d16sp -target-feature -vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -dotprod -target-feature -fp16fml -target-feature -bf16 -target-feature -mve.fp -target-feature -fpregs -target-feature -crypto -target-feature -sha2 -target-feature -aes -target-feature +strict-align -target-abi aapcs -mfloat-abi soft -Wunaligned-access -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/amr/myworkspace/Breath_Analyzer_FSM/tmp/1/CMakeFiles/CMakeScratch/TryCompile-axcjes -resource-dir /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/lib/clang/20 -dependency-file CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o -x c /Users/amr/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Arm Compiler for Embedded 6.23 -cc1 default target aarch64-arm-none-eabi]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/../include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /Users/amr/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.23.0/bin/armar --create -cr libcmTC_95dbb.a  CMakeFiles/cmTC_95dbb.dir/CMakeCCompilerABI.o && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
