/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'Breath_Analyzer_PY32F003x8+Target' 
 * Target:  'Target' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"



#endif /* RTE_COMPONENTS_H */
